// GENERATED by tool/gen_catalog.py — do not edit by hand.
//
/// Parent -> child muscle taxonomy. Maps each specific muscle to its parent
/// group and coarse body region, and lists the children per parent. Powers
/// exercise-detail muscle display and library grouping.
library;

abstract final class MuscleTaxonomy {
  /// Parent muscle groups, in display order.
  static const List<String> parents = [
    "Chest",
    "Back",
    "Shoulders",
    "Biceps",
    "Triceps",
    "Forearms",
    "Quadriceps",
    "Hamstrings",
    "Glutes",
    "Adductors",
    "Abductors",
    "Calves",
    "Hip Flexors",
    "Core",
    "Neck",
    "Full Body"
  ];

  /// Parent group -> the specific muscles it contains.
  static const Map<String, List<String>> children = {
    "Chest": [
      "Chest",
      "Upper Chest",
      "Lower Chest",
      "Pectorals",
      "Serratus Anterior"
    ],
    "Back": ["Lats", "Upper Back", "Lower Back", "Traps", "Back", "Spine"],
    "Shoulders": [
      "Front Delts",
      "Side Delts",
      "Rear Delts",
      "Shoulders",
      "Delts",
      "Rotator Cuff"
    ],
    "Biceps": ["Biceps", "Brachialis"],
    "Triceps": ["Triceps"],
    "Forearms": ["Forearms", "Forearm Flexors", "Forearm Extensors", "Grip"],
    "Quadriceps": ["Quadriceps", "Quads", "VMO"],
    "Hamstrings": ["Hamstrings"],
    "Glutes": ["Glutes", "Gluteus Medius", "Gluteus Minimus"],
    "Adductors": ["Adductors", "Pectineus", "Gracilis"],
    "Abductors": ["Abductors", "TFL"],
    "Calves": ["Calves", "Tibialis Anterior"],
    "Hip Flexors": ["Hip Flexors"],
    "Core": ["Abdominals", "Abs", "Obliques", "Core"],
    "Neck": ["Neck Flexors", "Neck Extensors"],
    "Full Body": ["Full Body", "Posterior Chain", "Cardio"],
  };

  static const Map<String, String> _parentOf = {
    "Chest": "Chest",
    "Upper Chest": "Chest",
    "Lower Chest": "Chest",
    "Pectorals": "Chest",
    "Serratus Anterior": "Chest",
    "Lats": "Back",
    "Upper Back": "Back",
    "Lower Back": "Back",
    "Traps": "Back",
    "Back": "Back",
    "Spine": "Back",
    "Front Delts": "Shoulders",
    "Side Delts": "Shoulders",
    "Rear Delts": "Shoulders",
    "Shoulders": "Shoulders",
    "Delts": "Shoulders",
    "Rotator Cuff": "Shoulders",
    "Biceps": "Biceps",
    "Brachialis": "Biceps",
    "Triceps": "Triceps",
    "Forearms": "Forearms",
    "Forearm Flexors": "Forearms",
    "Forearm Extensors": "Forearms",
    "Grip": "Forearms",
    "Quadriceps": "Quadriceps",
    "Quads": "Quadriceps",
    "VMO": "Quadriceps",
    "Hamstrings": "Hamstrings",
    "Glutes": "Glutes",
    "Gluteus Medius": "Glutes",
    "Gluteus Minimus": "Glutes",
    "Adductors": "Adductors",
    "Pectineus": "Adductors",
    "Gracilis": "Adductors",
    "Abductors": "Abductors",
    "TFL": "Abductors",
    "Calves": "Calves",
    "Tibialis Anterior": "Calves",
    "Hip Flexors": "Hip Flexors",
    "Legs": "Legs",
    "Abdominals": "Core",
    "Abs": "Core",
    "Obliques": "Core",
    "Core": "Core",
    "Neck Flexors": "Neck",
    "Neck Extensors": "Neck",
    "Full Body": "Full Body",
    "Posterior Chain": "Full Body",
    "Cardio": "Full Body",
  };

  static const Map<String, String> _regionOf = {
    "Chest": "chest",
    "Upper Chest": "chest",
    "Lower Chest": "chest",
    "Pectorals": "chest",
    "Serratus Anterior": "chest",
    "Lats": "back",
    "Upper Back": "back",
    "Lower Back": "back",
    "Traps": "back",
    "Back": "back",
    "Spine": "back",
    "Front Delts": "shoulders",
    "Side Delts": "shoulders",
    "Rear Delts": "shoulders",
    "Shoulders": "shoulders",
    "Delts": "shoulders",
    "Rotator Cuff": "shoulders",
    "Biceps": "arms",
    "Brachialis": "arms",
    "Triceps": "arms",
    "Forearms": "forearms",
    "Forearm Flexors": "forearms",
    "Forearm Extensors": "forearms",
    "Grip": "forearms",
    "Quadriceps": "legs",
    "Quads": "legs",
    "VMO": "legs",
    "Hamstrings": "legs",
    "Glutes": "legs",
    "Gluteus Medius": "legs",
    "Gluteus Minimus": "legs",
    "Adductors": "legs",
    "Pectineus": "legs",
    "Gracilis": "legs",
    "Abductors": "legs",
    "TFL": "legs",
    "Calves": "legs",
    "Tibialis Anterior": "legs",
    "Hip Flexors": "legs",
    "Legs": "legs",
    "Abdominals": "core",
    "Abs": "core",
    "Obliques": "core",
    "Core": "core",
    "Neck Flexors": "neck",
    "Neck Extensors": "neck",
    "Full Body": "full body",
    "Posterior Chain": "full body",
    "Cardio": "full body",
  };

  /// Parent group for a specific muscle, e.g. "Lats" -> "Back".
  static String parentOf(String muscle) => _parentOf[muscle.trim()] ?? 'Other';

  /// Coarse region for a specific muscle, e.g. "Lats" -> "back".
  static String regionOf(String muscle) => _regionOf[muscle.trim()] ?? 'other';

  /// Specific muscles under a parent group (empty if unknown).
  static List<String> childrenOf(String parent) => children[parent] ?? const [];
}
