import 'package:flutter/material.dart';
import 'package:gymlog/core/theme/app_colors.dart';

/// [explore_catalog.dart]
/// The curated Explore catalog: the typed data behind the Explore Programs
/// screen, deliberately split out of the screen file so (a) data and
/// presentation are separated and (b) the integrity test imports this typed
/// list directly instead of regex-scraping widget source.
///
/// v2 (2026-08): rebuilt from a 16-program research dataset spanning Full
/// Body, Upper/Lower, PPL, Bro Split, Arnold Split, PHUL, PHAT and GZCLP, at
/// beginner through advanced levels and across full-gym, dumbbell-only and
/// bodyweight-only equipment. Every program is a REAL multi-day plan: a
/// 6-day PPL stays a 6-day PPL on import, it does not collapse into one day.
///
/// EVERY non-conditioning-note TemplateSlot below is an exact entry in the
/// bundled Exercise Library (assets/db/exercises.json): no fuzzy fallbacks
/// resolving to the wrong movement. `explore_catalog_integrity_test` asserts
/// this on every CI run. This file is machine-generated by
/// `tool/gen_explore_catalog.py` from `tool/data/gym_routines_database.json`
///: do not hand-edit slot names; re-run the generator instead.

/// One slot in a program day.
///
/// [name] is either the EXACT canonical Exercise Library name (verified to
/// exist) when [isConditioningNote] is false, or a plain display label when
/// it is true. [reps] is the ORIGINAL programming target as written by the
/// source plan: a plain string because real programming is not always a
/// single integer ("5-8", "30-45 sec", "10 min", "AMRAP" all appear here).
///
/// A handful of conditioning/isometric moves (treadmill intervals, jumping
/// jacks, mountain climbers, an isometric towel curl) have no equivalent in
/// the Exercise Library. Rather than silently dropping them and quietly
/// changing the program, they ship as [isConditioningNote] slots: shown in
/// the UI as a text-only finisher row, never imported into a routine's
/// tracked exercises, never counted toward the exercise-count chip.
class TemplateSlot {
  final String name;
  final int sets;
  final String reps;
  final bool isConditioningNote;

  const TemplateSlot(
    this.name, {
    this.sets = 3,
    this.reps = '10',
    this.isConditioningNote = false,
  });
}

/// One training day inside a multi-day program.
class ProgramDay {
  final String label;
  final String focus;
  final List<TemplateSlot> slots;

  const ProgramDay({
    required this.label,
    required this.focus,
    required this.slots,
  });

  List<TemplateSlot> get importableSlots =>
      slots.where((s) => !s.isConditioningNote).toList();

  int get totalSets => slots.fold(0, (a, s) => a + s.sets);
}

/// Difficulty tiers, drives the colored pill on each card. A program can span
/// more than one tier (e.g. "Intermediate · Advanced").
enum TemplateLevel { beginner, intermediate, advanced }

/// Equipment footprint required to run a program, drives the equipment
/// filter and the card's equipment chip.
enum ProgramEquipment { fullGym, dumbbellOnly, bodyweight }

class RoutineTemplate {
  final String name;

  /// Programming family used to group the catalog (PPL, Upper/Lower, …).
  final String category;
  final List<TemplateLevel> levels;
  final ProgramEquipment equipment;

  /// Target muscle groups, human-readable and scannable. The FIRST muscle-like
  /// token drives the card's muscle glyph (see [ExploreTemplateCard]).
  final String focus;
  final String description;
  final List<ProgramDay> days;

  /// Exactly one template is the editor's spotlight, promoted to the hero
  /// "Featured" card at the top of the (unfiltered) Explore screen.
  final bool featured;

  const RoutineTemplate({
    required this.name,
    required this.category,
    required this.levels,
    required this.equipment,
    required this.focus,
    required this.description,
    required this.days,
    this.featured = false,
  });

  int get daysPerWeek => days.length;

  /// Card/preview title without the trailing equipment parenthetical
  /// (e.g. "Push Pull Legs: 6-Day High Frequency (Gym)" → "Push Pull Legs:
  /// 6-Day High Frequency"). The parenthetical is redundant because the
  /// equipment fact already renders as a chip in the card's metadata row.
  /// Presentation-only: [name] stays the canonical import/source key.
  String get displayName => name.replaceFirst(RegExp(r' \([^)]*\)$'), '');

  /// Everything before the first ": " — the program family name used when
  /// naming imported day-routines (e.g. "Push Pull Legs · Push A").
  String get shortName => name.contains(': ') ? name.split(': ').first : name;

  int get totalSlots => days.fold(0, (a, d) => a + d.slots.length);

  int get totalImportableSlots =>
      days.fold(0, (a, d) => a + d.importableSlots.length);

  /// Flattened importable slots across every day, in day order, used for
  /// the card's short exercise-name preview line.
  List<TemplateSlot> get previewSlots =>
      days.expand((d) => d.importableSlots).toList();

  int get totalSets => days.fold(0, (a, d) => a + d.totalSets);

  /// Lowest (most accessible) level a program is tagged with: used for the
  /// difficulty pill color when a program spans multiple tiers.
  TemplateLevel get primaryLevel =>
      days.isEmpty ? TemplateLevel.beginner : _lowest(levels);

  static TemplateLevel _lowest(List<TemplateLevel> levels) =>
      levels.reduce((a, b) => a.index < b.index ? a : b);

  String get levelLabel => levels
      .map((l) => switch (l) {
            TemplateLevel.beginner => 'Beginner',
            TemplateLevel.intermediate => 'Intermediate',
            TemplateLevel.advanced => 'Advanced',
          })
      .toSet()
      .join(' · ');

  /// Difficulty color, ON-TOKEN. Maps to the semantic palette so "amber" /
  /// "green" mean one value app-wide.
  Color get levelColor => switch (primaryLevel) {
        TemplateLevel.beginner => AppColors.success,
        TemplateLevel.intermediate => AppColors.accentText,
        TemplateLevel.advanced => AppColors.warning,
      };

  String get equipmentLabel => switch (equipment) {
        ProgramEquipment.fullGym => 'Full Gym',
        ProgramEquipment.dumbbellOnly => 'Dumbbell Only',
        ProgramEquipment.bodyweight => 'No Equipment',
      };

  IconData get equipmentIcon => switch (equipment) {
        ProgramEquipment.fullGym => Icons.fitness_center_rounded,
        ProgramEquipment.dumbbellOnly => Icons.sports_gymnastics_rounded,
        ProgramEquipment.bodyweight => Icons.accessibility_new_rounded,
      };

  /// Honest per-session estimate averaged across days: ~2.8 min per working
  /// set (work + rest) + warm-up, rounded to the nearest 5 minutes.
  int get estMinutes {
    if (days.isEmpty) return 0;
    final avgSets = totalSets / days.length;
    return (((avgSets * 2.8) + 8) / 5).round() * 5;
  }
}

/// Display order for the grouped sections.
const exploreCategoryOrder = <String>[
  'Push · Pull · Legs',
  'Upper · Lower',
  'Full Body',
  'Powerbuilding',
  'Bro Split',
  'Arnold Split',
  'Strength Progression',
];

const exploreTemplates = <RoutineTemplate>[
  // ---- full_body_beginner_3day_gym ----
  RoutineTemplate(
    name: 'Full Body: 3-Day Beginner (Gym)',
    category: 'Full Body',
    levels: [TemplateLevel.beginner],
    equipment: ProgramEquipment.fullGym,
    focus: 'Glutes · Lats · Quads',
    description:
        'Classic beginner full-body linear progression template (Starting-Strength lineage) rebalanced with RP-style accessory volume for aesthetics.',
    days: [
      ProgramDay(
        label: 'Day 1 - Full Body A',
        focus: 'Squat pattern, horizontal push/pull',
        slots: [
          TemplateSlot('Squat (Barbell)', sets: 3, reps: '5-8'),
          TemplateSlot('Bench Press (Barbell)', sets: 3, reps: '6-10'),
          TemplateSlot('Seated Cable Row', sets: 3, reps: '8-12'),
          TemplateSlot('Standing Calf Raise (Machine)', sets: 3, reps: '12-15'),
          TemplateSlot('Hanging Leg Raise', sets: 3, reps: '10-15'),
          TemplateSlot('Face Pull (Cable)', sets: 2, reps: '15-20'),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Full Body B',
        focus: 'Hinge pattern, vertical push/pull',
        slots: [
          TemplateSlot('Romanian Deadlift (Barbell)', sets: 3, reps: '8-10'),
          TemplateSlot('Overhead Press (Barbell)', sets: 3, reps: '6-10'),
          TemplateSlot('Cable Pulldown', sets: 3, reps: '8-12'),
          TemplateSlot('Bulgarian Split Squat (Dumbbell)',
              sets: 3, reps: '10 each leg'),
          TemplateSlot('Bicep Curl (Dumbbell)', sets: 2, reps: '10-12'),
          TemplateSlot('Cable Crunch', sets: 3, reps: '12-15'),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Full Body C',
        focus: 'Leg press pattern, incline push, row',
        slots: [
          TemplateSlot('Leg Press (Machine)', sets: 3, reps: '8-12'),
          TemplateSlot('Incline Bench Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Chest-Supported Row (Machine)', sets: 3, reps: '10-12'),
          TemplateSlot('Hip Thrust (Barbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Triceps Pushdown (Cable - Rope)',
              sets: 2, reps: '10-12'),
          TemplateSlot('Weighted Front Plank', sets: 3, reps: '30-45 sec'),
        ],
      ),
    ],
  ),

  // ---- upper_lower_4day_gym ----
  RoutineTemplate(
    name: 'Upper/Lower: 4-Day (Gym)',
    featured: true,
    category: 'Upper · Lower',
    levels: [TemplateLevel.intermediate],
    equipment: ProgramEquipment.fullGym,
    focus: 'Hamstrings · Glutes · Upper Back',
    description:
        'Standard evidence-based upper/lower template hitting each muscle 2x/week, consistent with frequency research (Schoenfeld et al.) and popularized by Jeff Nippard\'s Fundamentals series.',
    days: [
      ProgramDay(
        label: 'Day 1 - Upper A',
        focus: 'Chest/back strength + shoulders/arms',
        slots: [
          TemplateSlot('Bench Press (Barbell)', sets: 4, reps: '6-10'),
          TemplateSlot('Barbell Row', sets: 4, reps: '6-10'),
          TemplateSlot('Overhead Press (Barbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Cable Pulldown', sets: 3, reps: '10-12'),
          TemplateSlot('Lateral Raise (Dumbbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Barbell Curl', sets: 3, reps: '10-12'),
          TemplateSlot('Triceps Pushdown (Cable - Rope)',
              sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Lower A',
        focus: 'Quad emphasis',
        slots: [
          TemplateSlot('Squat (Barbell)', sets: 4, reps: '6-10'),
          TemplateSlot('Romanian Deadlift (Barbell)', sets: 3, reps: '8-10'),
          TemplateSlot('Leg Press (Machine)', sets: 3, reps: '10-12'),
          TemplateSlot('Seated Leg Curl (Machine)', sets: 3, reps: '10-12'),
          TemplateSlot('Standing Calf Raise (Machine)', sets: 4, reps: '12-15'),
          TemplateSlot('Hanging Leg Raise', sets: 3, reps: '12-15'),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Upper B',
        focus: 'Chest/back width + delts/arms',
        slots: [
          TemplateSlot('Incline Bench Press (Dumbbell)', sets: 4, reps: '8-12'),
          TemplateSlot('Chest-Supported Row (Machine)', sets: 4, reps: '8-12'),
          TemplateSlot('Shoulder Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Lateral Raise (Cable)', sets: 3, reps: '15'),
          TemplateSlot('Face Pull (Cable)', sets: 3, reps: '15'),
          TemplateSlot('Hammer Curl (Dumbbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Skull Crusher (Barbell)', sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 4 - Lower B',
        focus: 'Hamstring/glute emphasis',
        slots: [
          TemplateSlot('Deadlift (Barbell)', sets: 4, reps: '5-8'),
          TemplateSlot('Front Squat (Barbell)', sets: 3, reps: '8-10'),
          TemplateSlot('Bulgarian Split Squat (Dumbbell)',
              sets: 3, reps: '10 each leg'),
          TemplateSlot('Seated Leg Curl (Machine)', sets: 3, reps: '12-15'),
          TemplateSlot('Seated Calf Raise (Machine)', sets: 4, reps: '15-20'),
          TemplateSlot('Cable Crunch', sets: 3, reps: '12-15'),
        ],
      ),
    ],
  ),

  // ---- ppl_6day_gym ----
  RoutineTemplate(
    name: 'Push Pull Legs: 6-Day High Frequency (Gym)',
    category: 'Push · Pull · Legs',
    levels: [TemplateLevel.intermediate, TemplateLevel.advanced],
    equipment: ProgramEquipment.fullGym,
    focus: 'Biceps · Glutes · Lats',
    description:
        'Inspired by Jeff Nippard\'s Push/Pull/Legs hypertrophy programming (2x/week frequency per muscle, block-based exercise rotation) and RP volume landmarks.',
    days: [
      ProgramDay(
        label: 'Day 1 - Push A',
        focus: 'Chest emphasis',
        slots: [
          TemplateSlot('Bench Press (Barbell)', sets: 4, reps: '6-10'),
          TemplateSlot('Incline Bench Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Seated Shoulder Press (Machine)',
              sets: 3, reps: '8-12'),
          TemplateSlot('Cable Standing Fly', sets: 3, reps: '12-15'),
          TemplateSlot('Lateral Raise (Dumbbell)', sets: 3, reps: '15'),
          TemplateSlot('Triceps Pushdown (Cable - Rope)',
              sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Pull A',
        focus: 'Back thickness emphasis',
        slots: [
          TemplateSlot('Pull Up', sets: 4, reps: '6-10'),
          TemplateSlot('Barbell Row', sets: 3, reps: '8-10'),
          TemplateSlot('Seated Cable Row', sets: 3, reps: '10-12'),
          TemplateSlot('Face Pull (Cable)', sets: 3, reps: '15'),
          TemplateSlot('Barbell Curl', sets: 3, reps: '10-12'),
          TemplateSlot('Hammer Curl (Dumbbell)', sets: 2, reps: '12'),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Legs A',
        focus: 'Squat emphasis',
        slots: [
          TemplateSlot('Squat (Barbell)', sets: 4, reps: '6-8'),
          TemplateSlot('Romanian Deadlift (Barbell)', sets: 3, reps: '8-10'),
          TemplateSlot('Leg Press (Machine)', sets: 3, reps: '10-12'),
          TemplateSlot('Seated Leg Curl (Machine)', sets: 3, reps: '10-12'),
          TemplateSlot('Standing Calf Raise (Machine)', sets: 4, reps: '12-15'),
          TemplateSlot('Hanging Leg Raise', sets: 3, reps: '15'),
        ],
      ),
      ProgramDay(
        label: 'Day 4 - Push B',
        focus: 'Shoulder/triceps emphasis',
        slots: [
          TemplateSlot('Overhead Press (Barbell)', sets: 4, reps: '6-10'),
          TemplateSlot('Bench Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Lateral Raise (Cable)', sets: 4, reps: '15'),
          TemplateSlot('Dip', sets: 3, reps: '8-12'),
          TemplateSlot('Overhead Triceps Extension (Dumbbell)',
              sets: 3, reps: '10-12'),
          TemplateSlot('Cable Crunch', sets: 3, reps: '15'),
        ],
      ),
      ProgramDay(
        label: 'Day 5 - Pull B',
        focus: 'Back width emphasis',
        slots: [
          TemplateSlot('Deadlift (Barbell)', sets: 3, reps: '5'),
          TemplateSlot('Cable Pulldown', sets: 4, reps: '8-12'),
          TemplateSlot('T-Bar Row', sets: 3, reps: '8-10'),
          TemplateSlot('Reverse Fly (Machine)', sets: 3, reps: '15'),
          TemplateSlot('Cable Curl', sets: 3, reps: '10-12'),
          TemplateSlot('Preacher Curl (Barbell)', sets: 2, reps: '12'),
        ],
      ),
      ProgramDay(
        label: 'Day 6 - Legs B',
        focus: 'Posterior chain emphasis',
        slots: [
          TemplateSlot('Front Squat (Barbell)', sets: 3, reps: '8-10'),
          TemplateSlot('Hip Thrust (Barbell)', sets: 4, reps: '8-10'),
          TemplateSlot('Bulgarian Split Squat (Dumbbell)',
              sets: 3, reps: '10 each leg'),
          TemplateSlot('Seated Leg Curl (Machine)', sets: 3, reps: '12-15'),
          TemplateSlot('Seated Calf Raise (Machine)', sets: 4, reps: '15-20'),
          TemplateSlot('Kneeling Ab Wheel Roll-Out', sets: 3, reps: '10-12'),
        ],
      ),
    ],
  ),

  // ---- ppl_3day_gym ----
  RoutineTemplate(
    name: 'Push Pull Legs: 3-Day Low Frequency (Gym)',
    category: 'Push · Pull · Legs',
    levels: [TemplateLevel.beginner, TemplateLevel.intermediate],
    equipment: ProgramEquipment.fullGym,
    focus: 'Hamstrings · Chest · Biceps',
    description:
        'Single-pass PPL for lifters with only 3 days available; each muscle trained once/week so per-session volume is higher to compensate for lower frequency.',
    days: [
      ProgramDay(
        label: 'Day 1 - Push',
        focus: 'Chest, shoulders, triceps',
        slots: [
          TemplateSlot('Bench Press (Barbell)', sets: 4, reps: '6-10'),
          TemplateSlot('Incline Bench Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Overhead Press (Barbell)', sets: 3, reps: '8-10'),
          TemplateSlot('Lateral Raise (Dumbbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Dip', sets: 3, reps: '10-12'),
          TemplateSlot('Triceps Pushdown (Cable - Rope)',
              sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Pull',
        focus: 'Back and biceps',
        slots: [
          TemplateSlot('Deadlift (Barbell)', sets: 3, reps: '5-6'),
          TemplateSlot('Pull Up', sets: 4, reps: '8-10'),
          TemplateSlot('Barbell Row', sets: 3, reps: '8-10'),
          TemplateSlot('Face Pull (Cable)', sets: 3, reps: '15'),
          TemplateSlot('Barbell Curl', sets: 3, reps: '10-12'),
          TemplateSlot('Hammer Curl (Dumbbell)', sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Legs',
        focus: 'Quads, hamstrings, glutes, calves',
        slots: [
          TemplateSlot('Squat (Barbell)', sets: 4, reps: '6-10'),
          TemplateSlot('Romanian Deadlift (Barbell)', sets: 3, reps: '8-10'),
          TemplateSlot('Leg Press (Machine)', sets: 3, reps: '10-12'),
          TemplateSlot('Seated Leg Curl (Machine)', sets: 3, reps: '10-12'),
          TemplateSlot('Standing Calf Raise (Machine)', sets: 4, reps: '12-15'),
          TemplateSlot('Hanging Leg Raise', sets: 3, reps: '15'),
        ],
      ),
    ],
  ),

  // ---- bro_split_5day_gym ----
  RoutineTemplate(
    name: 'Bro Split: 5-Day Body-Part Split (Gym)',
    category: 'Bro Split',
    levels: [TemplateLevel.intermediate, TemplateLevel.advanced],
    equipment: ProgramEquipment.fullGym,
    focus: 'Triceps · Chest · Biceps',
    description:
        'Traditional bodybuilding body-part split (1x/week/muscle, high per-session volume). Frequency is below the 2x/week research optimum, so per-session volume is pushed toward MAV/MRV to compensate.',
    days: [
      ProgramDay(
        label: 'Day 1 - Chest',
        focus: 'Chest focus',
        slots: [
          TemplateSlot('Bench Press (Barbell)', sets: 4, reps: '6-10'),
          TemplateSlot('Incline Bench Press (Dumbbell)', sets: 4, reps: '8-12'),
          TemplateSlot('Chest Press (Machine)', sets: 3, reps: '10-12'),
          TemplateSlot('Cable Standing Fly', sets: 3, reps: '12-15'),
          TemplateSlot('Dip', sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Back',
        focus: 'Back focus',
        slots: [
          TemplateSlot('Deadlift (Barbell)', sets: 3, reps: '5-6'),
          TemplateSlot('Pull Up', sets: 4, reps: '6-10'),
          TemplateSlot('Barbell Row', sets: 4, reps: '8-10'),
          TemplateSlot('Seated Cable Row', sets: 3, reps: '10-12'),
          TemplateSlot('Cable Pulldown', sets: 3, reps: '10-12'),
          TemplateSlot('Face Pull (Cable)', sets: 3, reps: '15'),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Shoulders',
        focus: 'Shoulder focus',
        slots: [
          TemplateSlot('Overhead Press (Barbell)', sets: 4, reps: '6-10'),
          TemplateSlot('Shoulder Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Lateral Raise (Dumbbell)', sets: 4, reps: '12-15'),
          TemplateSlot('Lateral Raise (Cable)', sets: 3, reps: '15'),
          TemplateSlot('Reverse Fly (Machine)', sets: 4, reps: '15'),
          TemplateSlot('Shrug (Barbell)', sets: 3, reps: '12-15'),
        ],
      ),
      ProgramDay(
        label: 'Day 4 - Arms',
        focus: 'Biceps and triceps focus',
        slots: [
          TemplateSlot('Barbell Curl', sets: 4, reps: '8-12'),
          TemplateSlot('Bench Press - Close Grip (Barbell)',
              sets: 4, reps: '8-10'),
          TemplateSlot('Hammer Curl (Dumbbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Skull Crusher (Barbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Cable Curl', sets: 3, reps: '12-15'),
          TemplateSlot('Overhead Triceps Extension (Dumbbell)',
              sets: 3, reps: '12-15'),
        ],
      ),
      ProgramDay(
        label: 'Day 5 - Legs',
        focus: 'Full lower body',
        slots: [
          TemplateSlot('Squat (Barbell)', sets: 4, reps: '6-10'),
          TemplateSlot('Romanian Deadlift (Barbell)', sets: 3, reps: '8-10'),
          TemplateSlot('Leg Press (Machine)', sets: 3, reps: '10-12'),
          TemplateSlot('Leg Extension (Machine)', sets: 3, reps: '12-15'),
          TemplateSlot('Seated Leg Curl (Machine)', sets: 3, reps: '12-15'),
          TemplateSlot('Standing Calf Raise (Machine)', sets: 4, reps: '12-15'),
          TemplateSlot('Hanging Leg Raise', sets: 3, reps: '15'),
        ],
      ),
    ],
  ),

  // ---- arnold_split_6day_gym ----
  RoutineTemplate(
    name: 'Arnold Split: 6-Day (Gym)',
    category: 'Arnold Split',
    levels: [TemplateLevel.advanced],
    equipment: ProgramEquipment.fullGym,
    focus: 'Triceps · Biceps · Chest',
    description:
        'Classic Arnold Schwarzenegger-popularized chest+back / shoulders+arms / legs rotation, run twice through per week for 2x frequency per muscle at bodybuilding-level volume.',
    days: [
      ProgramDay(
        label: 'Day 1 - Chest & Back A',
        focus: 'Chest + back',
        slots: [
          TemplateSlot('Bench Press (Barbell)', sets: 4, reps: '6-10'),
          TemplateSlot('Pull Up', sets: 4, reps: '6-10'),
          TemplateSlot('Incline Bench Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Barbell Row', sets: 3, reps: '8-10'),
          TemplateSlot('Cable Standing Fly', sets: 3, reps: '12-15'),
          TemplateSlot('Seated Cable Row', sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Shoulders & Arms A',
        focus: 'Shoulders + arms',
        slots: [
          TemplateSlot('Overhead Press (Barbell)', sets: 4, reps: '6-10'),
          TemplateSlot('Barbell Curl', sets: 4, reps: '8-12'),
          TemplateSlot('Lateral Raise (Dumbbell)', sets: 4, reps: '12-15'),
          TemplateSlot('Skull Crusher (Barbell)', sets: 4, reps: '8-12'),
          TemplateSlot('Reverse Fly (Machine)', sets: 3, reps: '15'),
          TemplateSlot('Hammer Curl (Dumbbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Triceps Pushdown (Cable - Rope)',
              sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Legs A',
        focus: 'Squat emphasis',
        slots: [
          TemplateSlot('Squat (Barbell)', sets: 4, reps: '6-10'),
          TemplateSlot('Romanian Deadlift (Barbell)', sets: 3, reps: '8-10'),
          TemplateSlot('Leg Press (Machine)', sets: 3, reps: '10-12'),
          TemplateSlot('Seated Leg Curl (Machine)', sets: 3, reps: '10-12'),
          TemplateSlot('Standing Calf Raise (Machine)', sets: 4, reps: '12-15'),
          TemplateSlot('Hanging Leg Raise', sets: 3, reps: '15'),
        ],
      ),
      ProgramDay(
        label: 'Day 4 - Chest & Back B',
        focus: 'Chest + back, varied angles',
        slots: [
          TemplateSlot('Incline Bench Press (Barbell)', sets: 4, reps: '6-10'),
          TemplateSlot('Cable Pulldown', sets: 4, reps: '8-12'),
          TemplateSlot('Chest Press (Machine)', sets: 3, reps: '10-12'),
          TemplateSlot('T-Bar Row', sets: 3, reps: '8-10'),
          TemplateSlot('Dip', sets: 3, reps: '10-12'),
          TemplateSlot('Face Pull (Cable)', sets: 3, reps: '15'),
        ],
      ),
      ProgramDay(
        label: 'Day 5 - Shoulders & Arms B',
        focus: 'Shoulders + arms, varied angles',
        slots: [
          TemplateSlot('Shoulder Press (Dumbbell)', sets: 4, reps: '8-12'),
          TemplateSlot('Cable Curl', sets: 4, reps: '10-12'),
          TemplateSlot('Lateral Raise (Cable)', sets: 4, reps: '15'),
          TemplateSlot('Overhead Triceps Extension (Dumbbell)',
              sets: 4, reps: '10-12'),
          TemplateSlot('Reverse Fly (Dumbbell)', sets: 3, reps: '15'),
          TemplateSlot('Preacher Curl (Barbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Bench Press - Close Grip (Barbell)',
              sets: 3, reps: '8-10'),
        ],
      ),
      ProgramDay(
        label: 'Day 6 - Legs B',
        focus: 'Posterior chain emphasis',
        slots: [
          TemplateSlot('Front Squat (Barbell)', sets: 3, reps: '8-10'),
          TemplateSlot('Hip Thrust (Barbell)', sets: 4, reps: '8-10'),
          TemplateSlot('Bulgarian Split Squat (Dumbbell)',
              sets: 3, reps: '10 each leg'),
          TemplateSlot('Leg Extension (Machine)', sets: 3, reps: '12-15'),
          TemplateSlot('Seated Calf Raise (Machine)', sets: 4, reps: '15-20'),
          TemplateSlot('Cable Crunch', sets: 3, reps: '15'),
        ],
      ),
    ],
  ),

  // ---- phul_4day_gym ----
  RoutineTemplate(
    name: 'PHUL: Power Hypertrophy Upper Lower (Gym)',
    category: 'Powerbuilding',
    levels: [TemplateLevel.intermediate],
    equipment: ProgramEquipment.fullGym,
    focus: 'Quads · Glutes · Hamstrings',
    description:
        'Popular powerbuilding template: Upper Power / Lower Power / Upper Hypertrophy / Lower Hypertrophy. Power days use 3-5 rep heavy compounds; hypertrophy days use 8-12 rep accessory volume.',
    days: [
      ProgramDay(
        label: 'Day 1 - Upper Power',
        focus: 'Heavy compound upper',
        slots: [
          TemplateSlot('Bench Press (Barbell)', sets: 4, reps: '3-5'),
          TemplateSlot('Barbell Row', sets: 4, reps: '3-5'),
          TemplateSlot('Overhead Press (Barbell)', sets: 3, reps: '6-8'),
          TemplateSlot('Cable Pulldown', sets: 3, reps: '6-8'),
          TemplateSlot('Barbell Curl', sets: 2, reps: '8-10'),
          TemplateSlot('Triceps Pushdown (Cable - Rope)',
              sets: 2, reps: '8-10'),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Lower Power',
        focus: 'Heavy compound lower',
        slots: [
          TemplateSlot('Squat (Barbell)', sets: 4, reps: '3-5'),
          TemplateSlot('Deadlift (Barbell)', sets: 3, reps: '3-5'),
          TemplateSlot('Leg Press (Machine)', sets: 3, reps: '8-10'),
          TemplateSlot('Seated Leg Curl (Machine)', sets: 3, reps: '8-10'),
          TemplateSlot('Standing Calf Raise (Machine)', sets: 4, reps: '8-10'),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Upper Hypertrophy',
        focus: 'Volume upper',
        slots: [
          TemplateSlot('Incline Bench Press (Dumbbell)', sets: 4, reps: '8-12'),
          TemplateSlot('Seated Cable Row', sets: 4, reps: '8-12'),
          TemplateSlot('Shoulder Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Lateral Raise (Cable)', sets: 3, reps: '12-15'),
          TemplateSlot('Face Pull (Cable)', sets: 3, reps: '15'),
          TemplateSlot('Hammer Curl (Dumbbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Skull Crusher (Barbell)', sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 4 - Lower Hypertrophy',
        focus: 'Volume lower',
        slots: [
          TemplateSlot('Front Squat (Barbell)', sets: 4, reps: '8-12'),
          TemplateSlot('Romanian Deadlift (Barbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Bulgarian Split Squat (Dumbbell)',
              sets: 3, reps: '10 each leg'),
          TemplateSlot('Leg Extension (Machine)', sets: 3, reps: '12-15'),
          TemplateSlot('Seated Leg Curl (Machine)', sets: 3, reps: '12-15'),
          TemplateSlot('Seated Calf Raise (Machine)', sets: 4, reps: '12-15'),
          TemplateSlot('Hanging Leg Raise', sets: 3, reps: '15'),
        ],
      ),
    ],
  ),

  // ---- phat_5day_gym ----
  RoutineTemplate(
    name: 'PHAT: Power Hypertrophy Adaptive Training (Gym)',
    category: 'Powerbuilding',
    levels: [TemplateLevel.intermediate, TemplateLevel.advanced],
    equipment: ProgramEquipment.fullGym,
    focus: 'Lats · Biceps · Triceps',
    description:
        'Dr. Layne Norton\'s PHAT: 2 heavy power days (3-5 reps) + 3 hypertrophy days (8-15 reps), training every muscle twice weekly via undulating periodization.',
    days: [
      ProgramDay(
        label: 'Day 1 - Upper Power',
        focus: 'Heavy upper compounds',
        slots: [
          TemplateSlot('Bench Press (Barbell)', sets: 3, reps: '3-5'),
          TemplateSlot('Barbell Row', sets: 3, reps: '3-5'),
          TemplateSlot('Pull Up', sets: 3, reps: '5-8'),
          TemplateSlot('Overhead Press (Barbell)', sets: 3, reps: '5-8'),
          TemplateSlot('Barbell Curl', sets: 2, reps: '6-8'),
          TemplateSlot('Skull Crusher (Barbell)', sets: 2, reps: '6-8'),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Lower Power',
        focus: 'Heavy lower compounds',
        slots: [
          TemplateSlot('Squat (Barbell)', sets: 3, reps: '3-5'),
          TemplateSlot('Deadlift (Barbell)', sets: 3, reps: '3-5'),
          TemplateSlot('Leg Press (Machine)', sets: 3, reps: '8-10'),
          TemplateSlot('Seated Leg Curl (Machine)', sets: 2, reps: '8-10'),
          TemplateSlot('Standing Calf Raise (Machine)', sets: 3, reps: '8-10'),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Back & Shoulders Hypertrophy',
        focus: 'Volume back + delts',
        slots: [
          TemplateSlot('Cable Pulldown', sets: 4, reps: '8-12'),
          TemplateSlot('Seated Cable Row', sets: 4, reps: '8-12'),
          TemplateSlot('T-Bar Row', sets: 3, reps: '10-12'),
          TemplateSlot('Shoulder Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Lateral Raise (Dumbbell)', sets: 4, reps: '12-15'),
          TemplateSlot('Face Pull (Cable)', sets: 3, reps: '15'),
        ],
      ),
      ProgramDay(
        label: 'Day 4 - Lower Hypertrophy',
        focus: 'Volume lower',
        slots: [
          TemplateSlot('Front Squat (Barbell)', sets: 4, reps: '8-12'),
          TemplateSlot('Romanian Deadlift (Barbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Bulgarian Split Squat (Dumbbell)',
              sets: 3, reps: '10 each leg'),
          TemplateSlot('Leg Extension (Machine)', sets: 3, reps: '12-15'),
          TemplateSlot('Seated Leg Curl (Machine)', sets: 3, reps: '12-15'),
          TemplateSlot('Seated Calf Raise (Machine)', sets: 4, reps: '15-20'),
        ],
      ),
      ProgramDay(
        label: 'Day 5 - Chest & Arms Hypertrophy',
        focus: 'Volume chest + arms',
        slots: [
          TemplateSlot('Incline Bench Press (Dumbbell)', sets: 4, reps: '8-12'),
          TemplateSlot('Chest Press (Machine)', sets: 3, reps: '10-12'),
          TemplateSlot('Cable Standing Fly', sets: 3, reps: '12-15'),
          TemplateSlot('Barbell Curl', sets: 3, reps: '10-12'),
          TemplateSlot('Hammer Curl (Dumbbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Triceps Pushdown (Cable - Rope)',
              sets: 3, reps: '10-12'),
          TemplateSlot('Overhead Triceps Extension (Dumbbell)',
              sets: 3, reps: '10-12'),
        ],
      ),
    ],
  ),

  // ---- gzclp_gym ----
  RoutineTemplate(
    name: 'GZCLP: Tiered Linear Progression (Gym)',
    category: 'Strength Progression',
    levels: [TemplateLevel.beginner, TemplateLevel.intermediate],
    equipment: ProgramEquipment.fullGym,
    focus: 'Lats · Front Delts · Hamstrings',
    description:
        'Cody Lefever\'s GZCL Programme for Linear Progression: T1 heavy compound (5x3+AMRAP), T2 moderate secondary compound (3x10), T3 light accessory (3x15+).',
    days: [
      ProgramDay(
        label: 'Workout A1',
        focus: 'Squat T1',
        slots: [
          TemplateSlot('Squat (Barbell)',
              sets: 5, reps: '3 (+AMRAP on last set)'),
          TemplateSlot('Bench Press (Barbell)', sets: 3, reps: '10'),
          TemplateSlot('Cable Pulldown', sets: 3, reps: '15+'),
          TemplateSlot('Hanging Leg Raise', sets: 3, reps: '15+'),
        ],
      ),
      ProgramDay(
        label: 'Workout A2',
        focus: 'Overhead Press T1',
        slots: [
          TemplateSlot('Overhead Press (Barbell)',
              sets: 5, reps: '3 (+AMRAP on last set)'),
          TemplateSlot('Deadlift (Barbell)', sets: 3, reps: '10'),
          TemplateSlot('Barbell Row', sets: 3, reps: '15+'),
          TemplateSlot('Standing Calf Raise (Machine)', sets: 3, reps: '15+'),
        ],
      ),
      ProgramDay(
        label: 'Workout B1',
        focus: 'Bench Press T1',
        slots: [
          TemplateSlot('Bench Press (Barbell)',
              sets: 5, reps: '3 (+AMRAP on last set)'),
          TemplateSlot('Squat (Barbell)', sets: 3, reps: '10'),
          TemplateSlot('Seated Cable Row', sets: 3, reps: '15+'),
          TemplateSlot('Cable Crunch', sets: 3, reps: '15+'),
        ],
      ),
      ProgramDay(
        label: 'Workout B2',
        focus: 'Deadlift T1',
        slots: [
          TemplateSlot('Deadlift (Barbell)',
              sets: 5, reps: '3 (+AMRAP on last set)'),
          TemplateSlot('Overhead Press (Barbell)', sets: 3, reps: '10'),
          TemplateSlot('Pull Up', sets: 3, reps: '15+'),
          TemplateSlot('Bicep Curl (Dumbbell)', sets: 3, reps: '15+'),
        ],
      ),
    ],
  ),

  // ---- full_body_fatloss_4day_gym ----
  RoutineTemplate(
    name: 'Full Body Fat-Loss Circuit: 4-Day (Gym)',
    category: 'Full Body',
    levels: [TemplateLevel.beginner, TemplateLevel.intermediate],
    equipment: ProgramEquipment.fullGym,
    focus: 'Hamstrings · Lats · Triceps',
    description:
        'Full-body strength maintained via moderate-load, higher-rep sets (shorter rest) plus a short conditioning finisher: preserves muscle in a calorie deficit while adding an energy-expenditure component. Alternate A/B/A/B across the week.',
    days: [
      ProgramDay(
        label: 'Day 1 - Full Body A',
        focus: 'Squat, push, pull, core + conditioning',
        slots: [
          TemplateSlot('Squat (Barbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Chest Press (Machine)', sets: 3, reps: '12-15'),
          TemplateSlot('Seated Cable Row', sets: 3, reps: '12-15'),
          TemplateSlot('Leg Press (Machine)', sets: 3, reps: '15'),
          TemplateSlot('Lateral Raise (Dumbbell)', sets: 3, reps: '15'),
          TemplateSlot('Cable Crunch', sets: 3, reps: '20'),
          TemplateSlot('Incline Treadmill / Bike Intervals',
              sets: 1, reps: '10 min', isConditioningNote: true),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Full Body B',
        focus: 'Hinge, pull, push, core + conditioning',
        slots: [
          TemplateSlot('Romanian Deadlift (Barbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Cable Pulldown', sets: 3, reps: '12-15'),
          TemplateSlot('Shoulder Press (Dumbbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Seated Leg Curl (Machine)', sets: 3, reps: '15'),
          TemplateSlot('Triceps Pushdown (Cable - Rope)', sets: 3, reps: '15'),
          TemplateSlot('Hanging Leg Raise', sets: 3, reps: '15-20'),
          TemplateSlot('Rowing Machine / Stairmaster Intervals',
              sets: 1, reps: '10 min', isConditioningNote: true),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Full Body A (repeat)',
        focus: 'Squat, push, pull, core + conditioning',
        slots: [
          TemplateSlot('Squat (Barbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Chest Press (Machine)', sets: 3, reps: '12-15'),
          TemplateSlot('Seated Cable Row', sets: 3, reps: '12-15'),
          TemplateSlot('Leg Press (Machine)', sets: 3, reps: '15'),
          TemplateSlot('Lateral Raise (Dumbbell)', sets: 3, reps: '15'),
          TemplateSlot('Cable Crunch', sets: 3, reps: '20'),
          TemplateSlot('Incline Treadmill / Bike Intervals',
              sets: 1, reps: '10 min', isConditioningNote: true),
        ],
      ),
      ProgramDay(
        label: 'Day 4 - Full Body B (repeat)',
        focus: 'Hinge, pull, push, core + conditioning',
        slots: [
          TemplateSlot('Romanian Deadlift (Barbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Cable Pulldown', sets: 3, reps: '12-15'),
          TemplateSlot('Shoulder Press (Dumbbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Seated Leg Curl (Machine)', sets: 3, reps: '15'),
          TemplateSlot('Triceps Pushdown (Cable - Rope)', sets: 3, reps: '15'),
          TemplateSlot('Hanging Leg Raise', sets: 3, reps: '15-20'),
          TemplateSlot('Rowing Machine / Stairmaster Intervals',
              sets: 1, reps: '10 min', isConditioningNote: true),
        ],
      ),
    ],
  ),

  // ---- full_body_beginner_3day_dumbbell ----
  RoutineTemplate(
    name: 'Full Body: 3-Day Beginner (Dumbbell Only)',
    category: 'Full Body',
    levels: [TemplateLevel.beginner],
    equipment: ProgramEquipment.dumbbellOnly,
    focus: 'Glutes · Chest · Quads',
    description:
        'Full-body dumbbell template applying the same movement-pattern balance (squat/hinge/push/pull) as barbell full-body programs, for home lifters with dumbbells + a bench.',
    days: [
      ProgramDay(
        label: 'Day 1 - Full Body A',
        focus: 'Squat, press, row, hinge',
        slots: [
          TemplateSlot('Goblet Squat', sets: 3, reps: '10-12'),
          TemplateSlot('Bench Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Single-Arm Dumbbell Row', sets: 3, reps: '10-12 each'),
          TemplateSlot('Romanian Deadlift (Dumbbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Shoulder Press (Dumbbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Standing Calf Raise (Dumbbell)',
              sets: 3, reps: '15-20'),
          TemplateSlot('Lying Leg Raise', sets: 3, reps: '12-15'),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Full Body B',
        focus: 'Lunge, press, row, hinge',
        slots: [
          TemplateSlot('Bulgarian Split Squat (Dumbbell)',
              sets: 3, reps: '10 each leg'),
          TemplateSlot('Incline Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Renegade Row', sets: 3, reps: '10 each'),
          TemplateSlot('Dumbbell Deadlift', sets: 3, reps: '10-12'),
          TemplateSlot('Lateral Raise (Dumbbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Hammer Curl (Dumbbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Weighted Front Plank', sets: 3, reps: '30-45 sec'),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Full Body C',
        focus: 'Lunge, press, pull, hinge',
        slots: [
          TemplateSlot('Walking Lunge (Dumbbell)',
              sets: 3, reps: '12 each leg'),
          TemplateSlot('Floor Press (Barbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Pullover (Dumbbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Stiff-Legged Deadlift (Dumbbell)',
              sets: 3, reps: '10-12'),
          TemplateSlot('Reverse Fly (Dumbbell)', sets: 3, reps: '15'),
          TemplateSlot('Overhead Triceps Extension (Dumbbell)',
              sets: 3, reps: '10-12'),
          TemplateSlot('Russian Twist', sets: 3, reps: '15 each side'),
        ],
      ),
    ],
  ),

  // ---- upper_lower_4day_dumbbell ----
  RoutineTemplate(
    name: 'Upper/Lower: 4-Day (Dumbbell Only)',
    category: 'Upper · Lower',
    levels: [TemplateLevel.intermediate],
    equipment: ProgramEquipment.dumbbellOnly,
    focus: 'Glutes · Quads · Triceps',
    description:
        'Upper/lower frequency template adapted to dumbbells-only, preserving 2x/week per-muscle frequency for home lifters with a dumbbell set + bench.',
    days: [
      ProgramDay(
        label: 'Day 1 - Upper A',
        focus: 'Press + row emphasis',
        slots: [
          TemplateSlot('Bench Press (Dumbbell)', sets: 4, reps: '8-12'),
          TemplateSlot('Single-Arm Dumbbell Row', sets: 4, reps: '10-12 each'),
          TemplateSlot('Shoulder Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Pullover (Dumbbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Lateral Raise (Dumbbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Bicep Curl (Dumbbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Overhead Triceps Extension (Dumbbell)',
              sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Lower A',
        focus: 'Squat pattern emphasis',
        slots: [
          TemplateSlot('Goblet Squat', sets: 4, reps: '10-12'),
          TemplateSlot('Romanian Deadlift (Dumbbell)', sets: 4, reps: '10-12'),
          TemplateSlot('Bulgarian Split Squat (Dumbbell)',
              sets: 3, reps: '10 each leg'),
          TemplateSlot('Standing Calf Raise (Dumbbell)',
              sets: 4, reps: '15-20'),
          TemplateSlot('Lying Leg Raise', sets: 3, reps: '15-20'),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Upper B',
        focus: 'Incline + pull emphasis',
        slots: [
          TemplateSlot('Incline Press (Dumbbell)', sets: 4, reps: '8-12'),
          TemplateSlot('Renegade Row', sets: 4, reps: '10 each'),
          TemplateSlot('Arnold Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Reverse Fly (Dumbbell)', sets: 3, reps: '15'),
          TemplateSlot('Hammer Curl (Dumbbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Skull Crusher (Dumbbell)', sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 4 - Lower B',
        focus: 'Hinge + lunge emphasis',
        slots: [
          TemplateSlot('Walking Lunge (Dumbbell)',
              sets: 4, reps: '12 each leg'),
          TemplateSlot('Stiff-Legged Deadlift (Dumbbell)',
              sets: 4, reps: '10-12'),
          TemplateSlot('Dumbbell Step-Up', sets: 3, reps: '10 each leg'),
          TemplateSlot('Dumbbell Single Leg Calf Raise',
              sets: 4, reps: '12-15 each'),
          TemplateSlot('Russian Twist', sets: 3, reps: '15 each side'),
        ],
      ),
    ],
  ),

  // ---- ppl_6day_dumbbell ----
  RoutineTemplate(
    name: 'Push Pull Legs: 6-Day (Dumbbell Only)',
    category: 'Push · Pull · Legs',
    levels: [TemplateLevel.intermediate, TemplateLevel.advanced],
    equipment: ProgramEquipment.dumbbellOnly,
    focus: 'Glutes · Triceps · Lats',
    description:
        'High-frequency PPL template adapted for dumbbells-only home setups, keeping the same 2x/week per-muscle frequency as the gym version.',
    days: [
      ProgramDay(
        label: 'Day 1 - Push A',
        focus: 'Chest + shoulders + triceps',
        slots: [
          TemplateSlot('Bench Press (Dumbbell)', sets: 4, reps: '8-12'),
          TemplateSlot('Incline Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Shoulder Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Lateral Raise (Dumbbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Overhead Triceps Extension (Dumbbell)',
              sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Pull A',
        focus: 'Back + biceps',
        slots: [
          TemplateSlot('Single-Arm Dumbbell Row', sets: 4, reps: '10-12 each'),
          TemplateSlot('Renegade Row', sets: 3, reps: '10 each'),
          TemplateSlot('Pullover (Dumbbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Reverse Fly (Dumbbell)', sets: 3, reps: '15'),
          TemplateSlot('Hammer Curl (Dumbbell)', sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Legs A',
        focus: 'Squat pattern',
        slots: [
          TemplateSlot('Goblet Squat', sets: 4, reps: '10-12'),
          TemplateSlot('Romanian Deadlift (Dumbbell)', sets: 3, reps: '10-12'),
          TemplateSlot('Bulgarian Split Squat (Dumbbell)',
              sets: 3, reps: '10 each leg'),
          TemplateSlot('Standing Calf Raise (Dumbbell)',
              sets: 4, reps: '15-20'),
          TemplateSlot('Lying Leg Raise', sets: 3, reps: '15-20'),
        ],
      ),
      ProgramDay(
        label: 'Day 4 - Push B',
        focus: 'Chest + shoulders, varied angle',
        slots: [
          TemplateSlot('Floor Press (Barbell)', sets: 4, reps: '10-12'),
          TemplateSlot('Arnold Press (Dumbbell)', sets: 3, reps: '8-12'),
          TemplateSlot('Lateral Raise (Dumbbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Diamond Push Up', sets: 3, reps: '10-15'),
          TemplateSlot('Skull Crusher (Dumbbell)', sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 5 - Pull B',
        focus: 'Back + biceps, hinge emphasis',
        slots: [
          TemplateSlot('Dumbbell Deadlift', sets: 4, reps: '8-10'),
          TemplateSlot('Single-Arm Dumbbell Row', sets: 3, reps: '12-15 each'),
          TemplateSlot('Pullover (Dumbbell)', sets: 3, reps: '12-15'),
          TemplateSlot('Reverse Fly (Dumbbell)', sets: 3, reps: '15'),
          TemplateSlot('Bicep Curl (Dumbbell)', sets: 3, reps: '10-12'),
        ],
      ),
      ProgramDay(
        label: 'Day 6 - Legs B',
        focus: 'Lunge + posterior chain',
        slots: [
          TemplateSlot('Walking Lunge (Dumbbell)',
              sets: 4, reps: '12 each leg'),
          TemplateSlot('Stiff-Legged Deadlift (Dumbbell)',
              sets: 3, reps: '10-12'),
          TemplateSlot('Dumbbell Step-Up', sets: 3, reps: '10 each leg'),
          TemplateSlot('Dumbbell Single Leg Calf Raise',
              sets: 4, reps: '15-20 each'),
          TemplateSlot('Russian Twist', sets: 3, reps: '15 each side'),
        ],
      ),
    ],
  ),

  // ---- full_body_beginner_3day_bodyweight ----
  RoutineTemplate(
    name: 'Full Body: 3-Day Beginner (No Equipment)',
    category: 'Full Body',
    levels: [TemplateLevel.beginner],
    equipment: ProgramEquipment.bodyweight,
    focus: 'Glutes · Upper Back · Lats',
    description:
        'Zero-equipment full-body template covering all six major movement patterns (push, pull, squat, hinge/bridge, carry-equivalent core, calf) using furniture (table/chair/door/towel) instead of gym equipment.',
    days: [
      ProgramDay(
        label: 'Day 1 - Full Body A',
        focus: 'Push, pull, squat, core',
        slots: [
          TemplateSlot('Push Up', sets: 4, reps: '8-15'),
          TemplateSlot('Inverted Row', sets: 4, reps: '8-15'),
          TemplateSlot('Air Squat', sets: 3, reps: '15-20'),
          TemplateSlot('Glute Bridge', sets: 3, reps: '15-20'),
          TemplateSlot('Weighted Front Plank', sets: 3, reps: '30-45 sec'),
          TemplateSlot('Standing Calf Raise (Machine)', sets: 3, reps: '15-20'),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Full Body B',
        focus: 'Pike push, row, split squat, core',
        slots: [
          TemplateSlot('Pike Push-Up', sets: 3, reps: '8-12'),
          TemplateSlot('Towel Row', sets: 3, reps: '10-15'),
          TemplateSlot('Bulgarian Split Squat (Bodyweight)',
              sets: 3, reps: '10-12 each leg'),
          TemplateSlot('Superman Raise', sets: 3, reps: '12-15'),
          TemplateSlot('Bicycle Crunch', sets: 3, reps: '15-20'),
          TemplateSlot('Isometric Towel Curl',
              sets: 2, reps: '20-30 sec', isConditioningNote: true),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Full Body C',
        focus: 'Decline push, row, lunge, core',
        slots: [
          TemplateSlot('Decline Push Up', sets: 3, reps: '8-15'),
          TemplateSlot('Towel Row', sets: 3, reps: '10-15'),
          TemplateSlot('Walking Lunge', sets: 3, reps: '12 each leg'),
          TemplateSlot('One-Legged Glute Bridge', sets: 3, reps: '12 each leg'),
          TemplateSlot('Reverse Crunch', sets: 3, reps: '15-20'),
          TemplateSlot('Bench Dip', sets: 3, reps: '10-15'),
        ],
      ),
    ],
  ),

  // ---- ppl_6day_bodyweight ----
  RoutineTemplate(
    name: 'Push Pull Legs: 6-Day (No Equipment)',
    category: 'Push · Pull · Legs',
    levels: [TemplateLevel.intermediate, TemplateLevel.advanced],
    equipment: ProgramEquipment.bodyweight,
    focus: 'Glutes · Upper Back · Triceps',
    description:
        'Calisthenics PPL template using leverage/tempo/unilateral progressions in place of external load, keeping the same 2x/week per-muscle frequency as weighted PPL.',
    days: [
      ProgramDay(
        label: 'Day 1 - Push A',
        focus: 'Push-up variations',
        slots: [
          TemplateSlot('Push Up', sets: 4, reps: '12-20'),
          TemplateSlot('Pike Push-Up', sets: 3, reps: '8-12'),
          TemplateSlot('Diamond Push Up', sets: 3, reps: '10-15'),
          TemplateSlot('Bench Dip', sets: 3, reps: '10-15'),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Pull A',
        focus: 'Row variations',
        slots: [
          TemplateSlot('Inverted Row with Underhand Grip',
              sets: 4, reps: '10-15'),
          TemplateSlot('Towel Row', sets: 3, reps: '10-15'),
          TemplateSlot('Superman Raise', sets: 3, reps: '15'),
          TemplateSlot('Isometric Towel Curl',
              sets: 3, reps: '20-30 sec', isConditioningNote: true),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Legs A',
        focus: 'Squat + glute pattern',
        slots: [
          TemplateSlot('Air Squat', sets: 4, reps: '15-20'),
          TemplateSlot('Bulgarian Split Squat (Bodyweight)',
              sets: 3, reps: '12 each leg'),
          TemplateSlot('Glute Bridge', sets: 3, reps: '15-20'),
          TemplateSlot('Standing Calf Raise (Machine)', sets: 4, reps: '15-20'),
          TemplateSlot('Weighted Front Plank', sets: 3, reps: '30-45 sec'),
        ],
      ),
      ProgramDay(
        label: 'Day 4 - Push B',
        focus: 'Push-up variations, varied angle',
        slots: [
          TemplateSlot('Decline Push Up', sets: 4, reps: '10-15'),
          TemplateSlot('Pike Push-Up', sets: 3, reps: '8-12'),
          TemplateSlot('Close Grip Push Up', sets: 3, reps: '10-15'),
          TemplateSlot('Bench Dip', sets: 3, reps: '12-15'),
        ],
      ),
      ProgramDay(
        label: 'Day 5 - Pull B',
        focus: 'Row variations, varied angle',
        slots: [
          TemplateSlot('Towel Row', sets: 4, reps: '10-15'),
          TemplateSlot('Inverted Row - Underhand', sets: 3, reps: '10-15'),
          TemplateSlot('Superman Raise', sets: 3, reps: '15'),
          TemplateSlot('Isometric Towel Curl',
              sets: 3, reps: '20-30 sec', isConditioningNote: true),
        ],
      ),
      ProgramDay(
        label: 'Day 6 - Legs B',
        focus: 'Lunge + single-leg pattern',
        slots: [
          TemplateSlot('Walking Lunge', sets: 4, reps: '12 each leg'),
          TemplateSlot('One-Legged Glute Bridge', sets: 3, reps: '12 each leg'),
          TemplateSlot('Pistol Squat', sets: 3, reps: '8 each leg'),
          TemplateSlot('Dumbbell Single Leg Calf Raise',
              sets: 4, reps: '15-20 each'),
          TemplateSlot('Reverse Crunch', sets: 3, reps: '15-20'),
        ],
      ),
    ],
  ),

  // ---- full_body_fatloss_4day_bodyweight ----
  RoutineTemplate(
    name: 'Full Body HIIT Fat-Loss: 4-Day (No Equipment)',
    category: 'Full Body',
    levels: [TemplateLevel.beginner, TemplateLevel.intermediate],
    equipment: ProgramEquipment.bodyweight,
    focus: 'Glutes · Abs · Upper Back',
    description:
        'Alternate Circuit A/B/A/B across the week. Higher reps, short rest (30-45 sec), and cardio-pattern moves (mountain climbers, jumping jacks) added between strength moves to raise energy expenditure while preserving muscle.',
    days: [
      ProgramDay(
        label: 'Day 1 - Full Body Circuit A',
        focus: 'Push, squat, row, glute, core, conditioning',
        slots: [
          TemplateSlot('Push Up', sets: 3, reps: '15-20'),
          TemplateSlot('Air Squat', sets: 3, reps: '20-25'),
          TemplateSlot('Inverted Row', sets: 3, reps: '15-20'),
          TemplateSlot('Glute Bridge', sets: 3, reps: '20'),
          TemplateSlot('Mountain Climbers',
              sets: 3, reps: '30 sec', isConditioningNote: true),
          TemplateSlot('Weighted Front Plank', sets: 3, reps: '45 sec'),
        ],
      ),
      ProgramDay(
        label: 'Day 2 - Full Body Circuit B',
        focus: 'Lunge, pike push, back extension, core, conditioning',
        slots: [
          TemplateSlot('Walking Lunge', sets: 3, reps: '15 each leg'),
          TemplateSlot('Pike Push-Up', sets: 3, reps: '10-15'),
          TemplateSlot('Superman Raise', sets: 3, reps: '15-20'),
          TemplateSlot('Bicycle Crunch', sets: 3, reps: '20'),
          TemplateSlot('Jumping Jacks',
              sets: 3, reps: '40 sec', isConditioningNote: true),
          TemplateSlot('Standing Calf Raise (Machine)', sets: 3, reps: '20-25'),
        ],
      ),
      ProgramDay(
        label: 'Day 3 - Full Body Circuit A (repeat)',
        focus: 'Push, squat, row, glute, core, conditioning',
        slots: [
          TemplateSlot('Push Up', sets: 3, reps: '15-20'),
          TemplateSlot('Air Squat', sets: 3, reps: '20-25'),
          TemplateSlot('Inverted Row', sets: 3, reps: '15-20'),
          TemplateSlot('Glute Bridge', sets: 3, reps: '20'),
          TemplateSlot('Mountain Climbers',
              sets: 3, reps: '30 sec', isConditioningNote: true),
          TemplateSlot('Weighted Front Plank', sets: 3, reps: '45 sec'),
        ],
      ),
      ProgramDay(
        label: 'Day 4 - Full Body Circuit B (repeat)',
        focus: 'Lunge, pike push, back extension, core, conditioning',
        slots: [
          TemplateSlot('Walking Lunge', sets: 3, reps: '15 each leg'),
          TemplateSlot('Pike Push-Up', sets: 3, reps: '10-15'),
          TemplateSlot('Superman Raise', sets: 3, reps: '15-20'),
          TemplateSlot('Bicycle Crunch', sets: 3, reps: '20'),
          TemplateSlot('Jumping Jacks',
              sets: 3, reps: '40 sec', isConditioningNote: true),
          TemplateSlot('Standing Calf Raise (Machine)', sets: 3, reps: '20-25'),
        ],
      ),
    ],
  ),
];

/// Grouped by category in the curated [exploreCategoryOrder]. Computed ONCE
/// (top-level `final`, lazily initialized) rather than re-grouped on every
/// widget build.
final List<({String category, List<RoutineTemplate> items})> exploreSections =
    () {
  final byCategory = <String, List<RoutineTemplate>>{};
  for (final t in exploreTemplates) {
    byCategory.putIfAbsent(t.category, () => []).add(t);
  }
  return [
    for (final c in exploreCategoryOrder)
      if (byCategory[c] != null) (category: c, items: byCategory[c]!),
  ];
}();
